site_name: Tanaguru
pages:
- ['index.md', 'Home']
- ['user_doc.md', 'User Documentation']
- ['install_doc.md', 'Installation']
- ['developer_doc.md', 'Developer Documentation']
- ['robots-txt.md', 'Robots.txt']
- ['tanaguru-team.md', 'Tanaguru Team']

theme: readthedocs
repo_url: https://github.com/Tanaguru/Tanaguru
