site_name: Tanaguru
pages:
- ['index.md', 'Home']
- ['user-doc.md', 'User Documentation']
- ['install-webapp-doc.md', 'Installation', 'Web application installation']
- ['installu-cli-doc.md', 'Installation', 'Command Line Interface installation']
- ['developer-doc.md', 'Developer Documentation']
- ['robots-txt.md', 'Robots.txt']
- ['tanaguru-team.md', 'Tanaguru Team']

theme: readthedocs
repo_url: https://github.com/Tanaguru/Tanaguru
