site_name: Tanaguru
pages:
- ['index.md',                      'Home']
- ['user-doc.md',                   'User Documentation']
- ['prerequisites-webapp-doc.md',   'Installation Web Application','Prerequisites']
- ['install-webapp-doc.md',         'Installation Web Application','Installation']
- ['configuration-webapp-doc.md',   'Installation Web Application','Configuration']
- ['usage-webapp-doc.md',           'Installation Web Application','Usage']
- ['prerequisites-cli-doc.md',      'Installation Command Line Interface (CLI)','Prerequisites']
- ['install-cli-doc.md',            'Installation Command Line Interface (CLI)','Installation']
- ['usage-cli-doc.md',              'Installation Command Line Interface (CLI)','Usage']
- ['developer-doc.md',              'Developer Documentation']
- ['robots-txt.md',                 'Robots.txt']
- ['Tanaguru-meter.md',             'Tanaguru meter']
- ['tanaguru-team.md',              'Tanaguru Team']

theme: readthedocs
repo_url: https://github.com/Tanaguru/Tanaguru
